# Generated by Django 4.0.1 on 2022-01-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('email', models.CharField(max_length=100, unique=True, verbose_name='Email')),
                ('datatime', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
            ],
        ),
    ]
