# Generated by Django 4.0.1 on 2022-01-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='datatime',
            new_name='datetime',
        ),
    ]
