# Generated by Django 4.0.1 on 2022-01-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_person_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Time'),
        ),
    ]
